// Generated by CoffeeScript 1.3.1
(function() {
  var AuthorizeService;

  AuthorizeService = (function() {

    AuthorizeService.name = 'AuthorizeService';

    function AuthorizeService() {}

    AuthorizeService.prototype.canJoinServer = function(handShakeData, callback) {
      if (callback) {
        return callback(null, true);
      }
    };

    AuthorizeService.prototype.canJoinRoom = function(handShakeData, roomId, callback) {
      if (callback) {
        return callback(true);
      }
    };

    return AuthorizeService;

  })();

  exports.AuthorizeService = new AuthorizeService;

}).call(this);
