// Generated by CoffeeScript 1.3.1
(function() {
  var AuthorizeService;

  AuthorizeService = (function() {

    AuthorizeService.name = 'AuthorizeService';

    function AuthorizeService() {}

    AuthorizeService.prototype.canJoinServer = function(user, callback) {
      if (callback) {
        return callback(true);
      }
    };

    AuthorizeService.prototype.canJoinRoom = function(user, room, callback) {
      if (callback) {
        return callback(true);
      }
    };

    return AuthorizeService;

  })();

}).call(this);
