// Generated by CoffeeScript 1.3.1
(function() {
  var AuthorizeService, Room, User;

  User = require('../models/user').User;

  Room = require('../models/room').Room;

  AuthorizeService = (function() {

    AuthorizeService.name = 'AuthorizeService';

    function AuthorizeService() {}

    AuthorizeService.prototype.canJoinServer = function(handShakeData, callback) {
      var user;
      user = new User();
      user.userId = 1;
      user.username = "shawn";
      user.status = "online";
      handShakeData.user = user;
      if (callback) {
        return callback(null, true);
      }
    };

    AuthorizeService.prototype.canJoinRoom = function(handShakeData, roomId, callback) {
      if (callback) {
        return callback(true);
      }
    };

    AuthorizeService.prototype.getRoom = function(roomId, callback) {
      var room;
      room = new Room();
      room.roomId = roomId;
      return callback(room);
    };

    return AuthorizeService;

  })();

  exports.AuthorizeService = new AuthorizeService;

}).call(this);
