// Generated by CoffeeScript 1.3.1
(function() {
  var Room;

  Room = (function() {

    Room.name = 'Room';

    function Room() {}

    Room.prototype.users = [];

    Room.prototype.roomId = 0;

    Room.prototype.roomName = '';

    return Room;

  })();

  exports.Room = Room;

}).call(this);
