// Generated by CoffeeScript 1.3.1
(function() {
  var Room;

  Room = (function() {

    Room.name = 'Room';

    function Room(roomId, roomName, users) {
      this.roomId = roomId != null ? roomId : 0;
      this.roomName = roomName != null ? roomName : '';
      this.users = users != null ? users : [];
    }

    return Room;

  })();

  exports.Room = Room;

}).call(this);
