// Generated by CoffeeScript 1.3.1
(function() {
  var User;

  User = (function() {

    User.name = 'User';

    function User(userId, username, status, rooms) {
      this.userId = userId != null ? userId : 0;
      this.username = username != null ? username : '';
      this.status = status != null ? status : 'online';
      this.rooms = rooms != null ? rooms : [];
    }

    return User;

  })();

  exports.User = User;

}).call(this);
