// Generated by CoffeeScript 1.3.1
(function() {

  exports.Manager = require('./manager');

  exports.start = function(socket, options) {
    console.log(exports.Manager);
    return new exports.Manager(socket, options);
  };

}).call(this);
