// Generated by CoffeeScript 1.3.1
(function() {

  exports.Manager = require('./manager');

  exports.start = function(io, options) {
    return new exports.Manager(io, options);
  };

}).call(this);
