// Generated by CoffeeScript 1.3.1
(function() {

  exports.Manager = require('./manager');

  exports.chatsy = function(socket, options) {
    return new exports.Manager(socket, options);
  };

}).call(this);
