// Generated by CoffeeScript 1.3.1
(function() {
  var Manager;

  Manager = (function() {

    Manager.name = 'Manager';

    Manager.prototype.users = [];

    Manager.prototype.rooms = [];

    function Manager(socket, options) {
      this.socket = socket;
      this.options = options;
    }

    return Manager;

  })();

}).call(this);
