// Generated by CoffeeScript 1.3.1
(function() {
  var Manager, exports;

  Manager = (function() {

    Manager.name = 'Manager';

    Manager.prototype.users = [];

    Manager.prototype.rooms = [];

    function Manager(io, options) {
      var self;
      this.io = io;
      this.options = options;
      self = this;
      this.io.of('/chat').on('connection', function(socket) {
        console.log("connected");
        return socket.on('joinRoom', self.joinRoom);
      });
    }

    Manager.prototype.joinRoom = function(data) {
      return console.log("Room: ", data);
    };

    return Manager;

  })();

  exports = module.exports = Manager;

}).call(this);
