// Generated by CoffeeScript 1.3.1
(function() {
  var User;

  User = (function() {

    User.name = 'User';

    function User() {}

    User.prototype.userId = 0;

    User.prototype.username = '';

    User.prototype.status = 'online';

    return User;

  })();

}).call(this);
